# Generated by Django 4.1.2 on 2023-01-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cart_cartitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='user',
            new_name='cart',
        ),
    ]
